TicketHub/TicketHub/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketHub.Areas.Identity.Data;
using TicketHub.DataTransferObjects;
using TicketHub.Models;

namespace TicketHub.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
              return _context.Event != null ? 
                          View(await _context.Event.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Event'  is null.");
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Title,Date,Description")] CreateEvent createEvent)
        {
            
            var _event = new Event();
            if (ModelState.IsValid)
            {
                _event.Title = createEvent.Title;
                _event.Date = createEvent.Date;
                _event.Description = createEvent.Description;

                _context.Add(_event);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(_event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Date,Description")] Event @event)
        {
            if (id != @event.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Event == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Event == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Event'  is null.");
            }
            var @event = await _context.Event.FindAsync(id);
            if (@event != null)
            {
                _context.Event.Remove(@event);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return (_context.Event?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TicketHub/TicketHub/Controllers/TicketsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketHub.Areas.Identity.Data;
using TicketHub.DataTransferObjects;
using TicketHub.Models;

namespace TicketHub.Controllers
{
    
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TicketsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Lai atlasitu visus ticketus no visiem useriem
            // var applicationDbContext = _context.Ticket.Include(t => t.Event).Include(t => t.Seller);

            // Lai atlasitu tikai savus ticketus
            var applicationDbContext = _context.Ticket.Include(t => t.Event).Include(t => t.Seller).Where(e => e.SellerId == userId);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ticket == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Event)
                .Include(t => t.Seller)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var model = new CreateTicket();
            // Query for only the Events that belong to the logged-in User
            var users = _context.User.Where(e => e.Id == userId);

            ViewData["EventId"] = new SelectList(_context.Event, "Id", "Title");
            //ViewData["SellerId"] = new SelectList(users, "Id", "FirstName");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to

        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,EventId,SellerId,Price,Quantity,Row,Seat")] CreateTicket createTicket)
        {
            /** Visur kur vajag, lai dabutu userId. **/
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var ticket = new Ticket();
            //Check for duplicate Row and seat combinations in events with same title or id
            var eventTitle = _context.Event.Where(e => e.Id == createTicket.EventId).Select(e => e.Title).FirstOrDefault();
           // var existingTitle = _context.Event.FirstOrDefault(t => t.Title == eventTitle);
            var existingTicket = _context.Ticket.FirstOrDefault(t => t.EventId == createTicket.EventId && t.Row == createTicket.Row && t.Seat == createTicket.Seat);

            if (existingTicket != null )
            {
                ModelState.AddModelError("Seat", "A ticket with the same Row and Seat already exists.");
            }
            if (ModelState.IsValid)
            {
                    ticket.SellerId = userId;
                    ticket.EventId = createTicket.EventId;
                    ticket.Price = createTicket.Price;
                    ticket.Quantity = createTicket.Quantity;
                if (createTicket.Quantity == 1)
                {
                    ticket.Row = createTicket.Row;
                    ticket.Seat = createTicket.Seat;
                }

                _context.Add(ticket);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
             }

             ViewData["EventId"] = new SelectList(_context.Event, "Id", "Title", createTicket.EventId);
             //ViewData["SellerId"] = new SelectList(_context.User, "Id", "FirstName", createTicket.SellerId);

            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ticket == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Event, "Id", "Title", ticket.EventId);
            ViewData["SellerId"] = new SelectList(_context.User, "Id", "FirstName", ticket.SellerId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventId,SellerId,Price,Quantity, Row, Seat")] EditTicket editTicket)
        {
            //Pārbauda vai datubāzē vispār ir kaut viena biļete
            if (_context.Ticket == null)
            {
                return NotFound();
            }

            //inicializē mainīgo', kas glabā konkrētas biļetes identifikatoru
            var ticket = _context.Ticket.Find(id);
            //Ja šis identifikators netika atrasts ar _context.Ticket.Find(id), ticket ir bez vērtības
            if (ticket == null)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    ticket.SellerId = editTicket.SellerId;
                    ticket.EventId = editTicket.EventId;
                    ticket.Price = editTicket.Price;
                    ticket.Quantity = editTicket.Quantity;
                    ticket.Row = editTicket.Row;
                    ticket.Seat = editTicket.Seat;

                    _context.Update(ticket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventId"] = new SelectList(_context.Event, "Id", "Title", ticket.EventId);
            ViewData["SellerId"] = new SelectList(_context.User, "Id", "FirstName", ticket.SellerId);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ticket == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Event)
                .Include(t => t.Seller)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ticket == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Ticket'  is null.");
            }
            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket != null)
            {
                _context.Ticket.Remove(ticket);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return (_context.Ticket?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        //List ticket
        // GET: Tickets/List/5
        public IActionResult List(int? id)

        {
            var ticket = _context.Ticket
            .Include(t => t.Event)
            .FirstOrDefault(t => t.Id == id);


            if (id == null || _context.Ticket == null)
            {
                return NotFound();
            }


            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult List(int id)
        {
            var ticket  = _context.Ticket.Find(id);

            if (ticket == null) 
            { 
                return NotFound(); 
            }

            else if(ModelState.IsValid)
            {   if (ticket.isListed == false)
                {
                    ticket.isListed = true;
                    _context.Update(ticket);
                    _context.SaveChanges();
                }
                else if (ticket.isListed == true)
                {
                    ticket.isListed = false;
                    _context.Update(ticket);
                    _context.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }
    }
}

TicketHub/TicketHub/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Security.Claims
@using Microsoft.Extensions.Primitives
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicketHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TicketHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TicketHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer.GetString("Home")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer.GetString("Privacy")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">@Localizer.GetString("AddEvent")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">@Localizer.GetString("MyTickets")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PurchaseHistories" asp-action="Index">@Localizer.GetString("PurchaseHistory")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SaleHistories" asp-action="Index">@Localizer.GetString("SalesHistory")</a>
                        </li>
                    </ul>
                </div><div>
                    @Localizer.GetString("ChangeLanguage"):
                    <a href="/Home/SetCulture?culture=en-US">EN</a>
                    <a href="/Home/SetCulture?culture=lv-LV">LV</a>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TicketHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer.GetString("Privacy")</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>